global_seed: 0
ha: ffnn
ha_kw:
  input_channels: 1
  reference_channels: [0]
  fs: 16000
  stacks: 5
  n_mels: 64
  hidden_sizes: [1024, 1024]
  dropout: 0.0
  aggregate: False
  fusion_layer: null
  emb_dim: 128
  eps: 1.0e-7
  optimizer: Adam
  optimizer_kw:
    lr: 1.0e-4
  loss: mse
  loss_kw: null
  scheduler: null
  scheduler_kw: null
  grad_clip: null
  stft_kw:
    frame_length: 512
    hop_length: 128
  wav_norm: null
dataset:
  train: default
  train_kw:
    dirs:
      - data/vbdemand/noisy_trainset_28spk_wav
      - data/vbdemand/clean_trainset_28spk_wav
    segment_length: 4.0
    fs: 16000
    segment_strategy: random
    seed: 0
    regexp: "^(?!p226|p287).*$"
    n_files: all
  val: default
  val_kw:
    dirs:
      - data/vbdemand/noisy_trainset_28spk_wav
      - data/vbdemand/clean_trainset_28spk_wav
    segment_length: null
    fs: 16000
    segment_strategy: random
    seed: 0
    regexp: "^(p226|p287).*$"
    n_files: 100
trainer:
  workers: 4
  epochs: 100
  device: cuda
  train_batch_sampler: random
  train_batch_sampler_kw:
    batch_size: 32
    dynamic: False
    fs: 16000
    seed: 0
  val_batch_sampler: random
  val_batch_sampler_kw:
    batch_size: 1
    dynamic: False
    fs: 16000
    seed: 0
  ignore_checkpoint: False
  preload: False
  ddp: False
  rank: 0
  use_wandb: True
  profile: False
  val_metrics:
    pesq:
      fs: 16000
    estoi:
      fs: 16000
    snr: null
  val_period: 1
  use_amp: True
  save_on_epochs: []
